apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        db: rethinkdb
      name: rethinkdb-driver
    spec:
      ports:
        - port: 28015
          targetPort: 28015
      selector:
        db: rethinkdb
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      labels:
        db: rethinkdb
      name: rethinkdb-rc
    spec:
      replicas: 1
      selector:
        db: rethinkdb
        role: replicas
      template:
        metadata:
          labels:
            db: rethinkdb
            role: replicas
        spec:
          containers:
          - image: cedbossneo/rethinkdb-kubernetes:2.3
            name: rethinkdb
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            ports:
            - containerPort: 8080
              name: admin-port
            - containerPort: 28015
              name: driver-port
            - containerPort: 29015
              name: cluster-port
            volumeMounts:
            - mountPath: /data/rethinkdb_data
              name: rethinkdb-storage
          volumes:
          - name: rethinkdb-storage
            emptyDir: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        db: rethinkdb
      name: rethinkdb-ui
    spec:
      sessionAffinity: ClientIP
      ports:
        - port: 80
          targetPort: 8080
      type: LoadBalancer
      selector:
        db: rethinkdb
